// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as AppModuleCss from "./App.module.css";

var css = AppModuleCss;

function About(Props) {
  return React.createElement("div", {
              className: css.app
            }, React.createElement("header", {
                  className: css.appHeader
                }, React.createElement("p", undefined, "About Page "), React.createElement("a", {
                      className: css.appLink,
                      href: "https://reasonml.github.io/reason-react",
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, "Learn Reason React")));
}

var make = About;

export {
  css ,
  make ,
  
}
/* css Not a pure module */
