// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.js";

Jest.test("addition", (function (param) {
        return Jest.Expect[/* toBe */2](7, Jest.Expect[/* expect */0](7));
      }));

export {
  
}
/*  Not a pure module */
