// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";

function $$Error(Props) {
  var code = Props.code;
  return React.createElement("div", undefined, code !== 404 ? "An error occurred!" : "Couldn't find that page!");
}

var make = $$Error;

export {
  make ,
  
}
/* react Not a pure module */
