// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Router from "./Router.bs.js";
import * as Intercom from "./Intercom.bs.js";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ServiceWorker from "./serviceWorker";
import * as IndexModuleCss from "./index.module.css";

var _css = IndexModuleCss;

function register_service_worker(prim) {
  ServiceWorker.register();
  return /* () */0;
}

function unregister_service_worker(prim) {
  ServiceWorker.unregister();
  return /* () */0;
}

Intercom.boot({
      app_id: APP_ID,
      created_at: new Date()
    });

Intercom.update(/* () */0);

ReactDOMRe.renderToElementWithId(React.createElement(Router.make, { }), "root");

ServiceWorker.unregister();

export {
  _css ,
  register_service_worker ,
  unregister_service_worker ,
  
}
/* _css Not a pure module */
