// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE


function boot(data) {
  Intercom("boot", data);
  return /* () */0;
}

function track($$event) {
  Intercom("trackEvent", $$event);
  return /* () */0;
}

function update($$event) {
  Intercom("update", $$event);
  return /* () */0;
}

export {
  boot ,
  track ,
  update ,
  
}
/* No side effect */
