// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as About from "./About.bs.js";
import * as $$Error from "./Error.bs.js";
import * as React from "react";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

function Router(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url[/* path */0];
  if (match) {
    if (match[0] === "about") {
      if (match[1]) {
        return React.createElement($$Error.make, {
                    code: 404
                  });
      } else {
        return React.createElement(About.make, { });
      }
    } else {
      return React.createElement($$Error.make, {
                  code: 404
                });
    }
  } else {
    return React.createElement(App.make, { });
  }
}

var make = Router;

export {
  make ,
  
}
/* App Not a pure module */
